[dataset]
filename = "./dataset/ml-100k/u.data"
sep = "\t"
num_negatives = 4
engine = "c"

[dataloader.train]
batch_size = 256
shuffle = true

[model.gmf]
latent_dim = 32
[model.mlp]
latent_dim = 32
layer_nums_list = [64, 32, 16, 8]

[trainer]
epochs = 20
learning_rate = 0.001
pretrain = false
