[dataset]
filename = "./dataset/ml-100k/u.data"
sep = "\t"
num_negatives = 4

[dataloader.train]
batch_size = 1024
shuffle = true
[dataloader.valid]
batch_size = 1024
shuffle = false

[model.gmf]
latent_dim = 8
[model.mlp]
latent_dim = 8
layer_nums_list = [16, 32, 16, 8]

[trainer]
epochs = 200
weight_decay = 0.01
pretran = false
